### ISSUE TITLE
Error on loading library list - Export Tools

### ISSUE THREAD

**Issue by usershield001** [usershield001/reimagined-octo-fiesta#1]
ExportTools: V 2.0.0.5
PMS 1.18.0.1913
plex web Version 4.10.1
system NVIDIA Shield

Hi 
after update PMS and plex web/app i have this error

2019-10-20 18:18:19,036 (2db162d4f0) :  CRITICAL (sandbox:303) - Exception when calling function 'ValidatePrefs' (most recent call last):
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-e5cc93306/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
    result = f(*args, **kwargs)
  File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/__init__.py", line 462, in ValidatePrefs
    Thread.Create(sectionList(), globalize=True)
  File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/__init__.py", line 151, in sectionList
    with io.open(prefsFile) as json_file:
TypeError: bad argument type for built-in operation

Do you have an idea where this comes from?

I read the post https://github.com/ukdtom/ExportTools.bundle/issues/103
but don't works
Thanks

**Comment by usershield001** [comment]
Sorry. Export Tools ver 2.0.0.7

**Comment by usershield001** [comment]
if I use a URL to launch Export tools the response is

<?xml version="1.0" encoding="ISO-8859-1"?>
<Response status="TypeError: cannot concatenate 'str' and 'NoneType' objects" code="2000">
<Traceback>Traceback (most recent call last): File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-e5cc93306/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request result = f(**d) File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/__init__.py", line 70, in launch playlist=playlist) File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/ExportTools.bundle/Contents/Code/output.py", line 74, in getOutFileName newtitle + '-' + level + timestr + extension) TypeError: cannot concatenate 'str' and 'NoneType' objects </Traceback>
</Response>
